// This file is generated by digen. DO NOT EDIT.
package testdata

import (
  "time"
  logosSet "github.com/loilo-inc/logos/set"
)

func (d *D) GetString() string {
  return d.Get("String").(string)
}

func (b *B) SetString(v string) {
  b.Set("String", v)
}

func (d *D) GetSSet() logosSet.StringSet {
  return d.Get("SSet").(logosSet.StringSet)
}

func (b *B) SetSSet(v logosSet.StringSet) {
  b.Set("SSet", v)
}

func (d *D) GetSlice() []int {
  return d.Get("Slice").([]int)
}

func (b *B) SetSlice(v []int) {
  b.Set("Slice", v)
}

func (d *D) GetSlicePtr() *[]int {
  return d.Get("SlicePtr").(*[]int)
}

func (b *B) SetSlicePtr(v *[]int) {
  b.Set("SlicePtr", v)
}

func (d *D) GetSliceWithLen() [1]int {
  return d.Get("SliceWithLen").([1]int)
}

func (b *B) SetSliceWithLen(v [1]int) {
  b.Set("SliceWithLen", v)
}

func (d *D) GetSliceWithLenPtr() *[1]int {
  return d.Get("SliceWithLenPtr").(*[1]int)
}

func (b *B) SetSliceWithLenPtr(v *[1]int) {
  b.Set("SliceWithLenPtr", v)
}

func (d *D) GetSliceOfSlice() [][]int {
  return d.Get("SliceOfSlice").([][]int)
}

func (b *B) SetSliceOfSlice(v [][]int) {
  b.Set("SliceOfSlice", v)
}

func (d *D) GetSliceOfSliceWithLen() [1][1]int {
  return d.Get("SliceOfSliceWithLen").([1][1]int)
}

func (b *B) SetSliceOfSliceWithLen(v [1][1]int) {
  b.Set("SliceOfSliceWithLen", v)
}

func (d *D) GetSliceOfSLicePtr() *[][]int {
  return d.Get("SliceOfSLicePtr").(*[][]int)
}

func (b *B) SetSliceOfSLicePtr(v *[][]int) {
  b.Set("SliceOfSLicePtr", v)
}

func (d *D) GetSliceOfSliceWithLenPtr() *[1][1]int {
  return d.Get("SliceOfSliceWithLenPtr").(*[1][1]int)
}

func (b *B) SetSliceOfSliceWithLenPtr(v *[1][1]int) {
  b.Set("SliceOfSliceWithLenPtr", v)
}

func (d *D) GetTimeStr() time.Time {
  return d.Get("TimeStr").(time.Time)
}

func (b *B) SetTimeStr(v time.Time) {
  b.Set("TimeStr", v)
}

func (d *D) GetTimePtr() *time.Time {
  return d.Get("TimePtr").(*time.Time)
}

func (b *B) SetTimePtr(v *time.Time) {
  b.Set("TimePtr", v)
}

func (d *D) GetIface() interface{} {
  return d.Get("Iface").(interface{})
}

func (b *B) SetIface(v interface{}) {
  b.Set("Iface", v)
}

func (d *D) GetStruct() struct{} {
  return d.Get("Struct").(struct{})
}

func (b *B) SetStruct(v struct{}) {
  b.Set("Struct", v)
}
